syntax = "proto3";
import "grpc-common.proto";
option java_multiple_files = true;
option java_package = "com.xxx.product.grpc";

message ProductGrpc {
  string id = 1;
  string product_name = 2;
  string product_description = 3;
  string product_code = 4;
}

message ProductGrpcInput {
  repeated string product_name = 1;
  repeated string product_code = 2;
  common.GrpcPagination page_info = 3;
}

message ProductGrpcResponse {
  string message = 1;
  repeated ProductGrpc data = 2;
  common.GrpcPagination page_info = 3;
}

service ProductService {
  rpc findProduct(ProductGrpcInput) returns (ProductGrpcResponse);
  rpc updateProduct(ProductGrpc) returns (ProductGrpcResponse);
  rpc deleteProduct(ProductGrpcInput) returns (ProductGrpcResponse);
}