syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.xxx.product.grpc";

message ProductGrpc {
  string id = 1;
  string product_name = 2;
  string product_description = 3;
  string product_code = 4;
}

message ProductGrpcInput {
  repeated string product_name = 1;
  repeated string product_code = 2;
  int64 current_page = 3;
  int64 page_size = 4;
}

message ProductGrpcResponse {
  string message = 1;
  repeated ProductGrpc data = 2;
  int64 current_page = 3;
  int64 total_record = 4;
}

service ProductService {
  rpc findProduct(ProductGrpcInput) returns (ProductGrpcResponse);
  rpc updateProduct(ProductGrpc) returns (ProductGrpcResponse);
  rpc deleteProduct(ProductGrpcInput) returns (ProductGrpcResponse);
}