syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.xxx.user.grpc";

message UserGrpc {
  string user_id = 1;
  string username = 2;
  string email = 3;
  string phone = 4;
  repeated string roles = 5;
  string full_name = 6;
}

message UserGrpcInput {
  repeated string username = 1;
  repeated string email = 2;
  int64 current_page = 3;
  int64 page_size = 4;
}

message UserGrpcResponse {
  string message = 1;
  repeated UserGrpc data = 2;
  int64 current_page = 3;
  int64 total_record = 4;
}

service UserService {
  rpc findUser(UserGrpcInput) returns (UserGrpcResponse);
  rpc findUsers(stream UserGrpcInput) returns (UserGrpcResponse);
  rpc updateUser(UserGrpc) returns (UserGrpcResponse);
  rpc deleteUser(UserGrpcInput) returns (UserGrpcResponse);
}