syntax = "proto3";
import "common/grpc-common.proto";

option java_multiple_files = true;
option java_package = "com.xxx.user.grpc";

message UserGrpc {
  int64 user_id = 1;
  string username = 2;
  string email = 3;
  string phone = 4;
  string full_name = 5;
  repeated RoleGrpc roles = 6;
}

message RoleGrpc {
  int64 role_id = 1;
  string code = 2;
  string value = 3;
  repeated PermissionGrpc permissions = 4;
}

message PermissionGrpc {
  int64 permission_id = 1;
  string code = 2;
  string value = 3;
}

message UserTokenGrpc {
  string token = 1;
}

message UserLoginGrpcInput {
  string username = 1;
  string password = 2;
}

message UserGrpcInput {
  repeated string username = 1;
  repeated string email = 2;
  common.GrpcPagination page_info = 3;
}

message UserGrpcRegister {
  string username = 1;
  string email = 2;
  string password = 3;
}

message UserGrpcResponse {
  string message = 1;
  repeated UserGrpc data = 2;
  common.GrpcPagination page_info = 3;
}

message RoleGrpcResponse {
  repeated RoleGrpc data = 1;
  common.GrpcPagination page_info = 2;
}

message PermissionGrpcResponse {
  repeated PermissionGrpc data = 1;
  common.GrpcPagination page_info = 2;
}

service UserGrpcService {
  rpc findUser(UserGrpcInput) returns (UserGrpcResponse);
  rpc findUsers(stream UserGrpcInput) returns (UserGrpcResponse);
  rpc updateUser(UserGrpc) returns (UserGrpcResponse);
  rpc deleteUser(UserGrpcInput) returns (UserGrpcResponse);
  rpc registerUser(UserGrpcRegister) returns (UserTokenGrpc);
  rpc loginUser(UserLoginGrpcInput) returns (UserTokenGrpc);
}

service RoleGrpcService {
  rpc findRole(RoleGrpc) returns (RoleGrpcResponse);
  rpc findRoleStream(stream RoleGrpc) returns (RoleGrpcResponse);
  rpc createRole(RoleGrpc) returns (RoleGrpcResponse);
  rpc updateRole(RoleGrpc) returns (RoleGrpcResponse);
  rpc deleteRole(RoleGrpc) returns (RoleGrpcResponse);
}

service PermissionGrpcService {
  rpc findPermission(PermissionGrpc) returns (PermissionGrpcResponse);
  rpc findPermissionStream(stream PermissionGrpc) returns (PermissionGrpcResponse);
  rpc createPermission(PermissionGrpc) returns (PermissionGrpcResponse);
  rpc updatePermission(PermissionGrpc) returns (PermissionGrpcResponse);
  rpc deletePermission(PermissionGrpc) returns (PermissionGrpcResponse);
}